smartgov-client:
  build: ./client
  ports:
   - "3000:3000"
  command: npm run start-dev 
  volumes:
   - ./client:/usr/src/app
  links:
   - smartgov-server
   
smartgov-server:
  build: ./server
  ports:
   - "3001:3001"
  command: npm run start-dev
  volumes:
   - ./server:/usr/src/app
  links:
   - smartgov-redis
   
smartgov-redis:
  image: redis
  ports:
   - "6379:6379"


nginx:
    image: nginx
    ports:
     - "80:80"
    volumes:
     - ./proxy/conf.d:/etc/nginx/conf.d
    links:
     - smartgov-client
     - smartgov-server